site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:
  - url: .
    start_path: core/_adoc-ug
    branches: HEAD
  - url: .
    start_path: core/plugins/jdo/_adoc
    branches: HEAD
  - url: .
    start_path: core/security/_adoc
    branches: HEAD
  - url: .
    start_path: core/testsupport/_adoc
    branches: HEAD
  - url: .
    start_path: core/viewer-restfulobjects/_adoc
    branches: HEAD
  - url: .
    start_path: core/viewer-wicket/_adoc
    branches: HEAD
  - url: .
    branches: HEAD
    start_path: core/_adoc-rg
  - url: .
    start_path: examples/apps/helloworld/_adoc
    branches: HEAD
  - url: .
    start_path: examples/apps/simpleapp/_adoc
    branches: HEAD
  - url: .
    branches: HEAD
    start_path: extensions/asciidoc/_adoc
  - url: .
    branches: HEAD
    start_path: extensions/markdown/_adoc
  - url: .
    branches: HEAD
    start_path: extensions/fixtures/_adoc
  - url: .
    branches: HEAD
    start_path: extensions/secman/_adoc
  - url: .
    branches: HEAD
    start_path: extensions/specsupport/_adoc
  - url: .
    branches: HEAD
    start_path: extensions/viewer-wicket-excel/_adoc
  - url: .
    branches: HEAD
    start_path: examples/apps/demo/_adoc
  - url: .
    branches: HEAD
    start_path: antora/components/downloads
  - url: .
    branches: HEAD
    start_path: antora/components/support
  - url: .
    branches: HEAD
    start_path: antora/components/toc

ui:
  bundle:
    url: antora/theme/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    page-toc: ""
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
