site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/security
      branches: HEAD
    - url: .
      start_path: antora/components/toc
      branches: HEAD

# core
    - url: .
      start_path: core/security/api/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/security/bypass/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/security/shiro/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/security/keycloak/src/main/doc # security
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/security/secman/src/main/doc # security secman
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/api/src/main/doc # security secman
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/encryption-jbcrypt/src/main/doc # security secman
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/model/src/main/doc # security secman
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/persistence-jdo/src/main/doc # security secman
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/realm-shiro/src/main/doc # security secman
      branches: HEAD


ui:
  bundle:
    url: ../isis-antora/build/ui-bundle.zip
#    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    #url: ./antora/theme/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
