language: node_js

node_js:
  - "lts/*"

before_install:
  - chmod +x gradlew

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - joerg.rade60@gmail.com
    on_success: change
    on_failure: always


script: ./gradlew test
